### ISSUE TITLE
compass error

### ISSUE THREAD

**Issue by klode** [blai/grunt-express-angular-example#3]
I just cloned the project and followed your directions and I get the following error when I run "grunt server"

```
    error app/styles/main.scss (Line 247 of app/bower_components/bootstrap-sass/lib/_mixins.scss: Invalid CSS after "...-shadow($shadow": expected ")", was "...) {")
```

**Comment by blai** [comment]
what version of sass do you use? I have 3.2.8, I think the latest is 3.2.10

**Comment by klode** [comment]
Thanks! 
I had sass version 3.1.5 updated to 3.2.10 and works.
